services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: starter
    region: oregon
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: streamlit-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.enableCORS false
    plan: free
    region: oregon
    autoDeploy: true
